<Project>

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <AssemblyName>SVS_$(MSBuildProjectName.Replace(".SVS", ""))</AssemblyName>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <DefineConstants>$(DefineConstants);SVS</DefineConstants>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <DefineConstants>$(DefineConstants);SVS</DefineConstants>
  </PropertyGroup>

  <Target Name="PostBuild" AfterTargets="PostBuildEvent">
    <Exec Command="IF EXIST $(SolutionDir)PostBuild.bat CALL &quot;$(SolutionDir)PostBuild.bat&quot; SVS $(TargetPath) $(SolutionDir)" />
  </Target>

</Project>