<Project>

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <AssemblyName>AC_$(MSBuildProjectName.Replace(".AC", ""))</AssemblyName>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <DefineConstants>$(DefineConstants);AC</DefineConstants>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <DefineConstants>$(DefineConstants);AC</DefineConstants>
  </PropertyGroup>

  <Target Name="PostBuild" AfterTargets="PostBuildEvent">
    <Exec Command="IF EXIST $(SolutionDir)PostBuild.bat CALL &quot;$(SolutionDir)PostBuild.bat&quot; AC $(TargetPath) $(SolutionDir)" />
  </Target>

</Project>