<Project>
  <PropertyGroup>
		<!-- This is the master version, only change this one -->
		<Version>0.6.0.0</Version>
    </PropertyGroup>

	<!-- Create a release zip file (after successful Release build) -->
	<Target Name="CreateReleaseZip" AfterTargets="Build" Condition="'$(Configuration)' == 'Release'">
		<PropertyGroup>
			<CopyDir>$(OutputPath)\..\TEMP_COPY_$(AssemblyName)</CopyDir>
		</PropertyGroup>
		<ItemGroup>
			<BuildFiles Include="$(OutputPath)\**\*" Exclude="**\*.tmp"/>
		</ItemGroup>

		<RemoveDir Directories="$(CopyDir)" />
		<Copy DestinationFolder="$(CopyDir)\BepInEx\plugins\IDontHaveIdea\%(RecursiveDir)" SourceFiles="@(BuildFiles)" />
		<!-- https://learn.microsoft.com/en-us/visualstudio/msbuild/zipdirectory-task?view=vs-2022 -->
		<ZipDirectory SourceDirectory="$(CopyDir)" DestinationFile="$(OutputPath)\..\$(AssemblyName)_v$(Version).zip" Overwrite="true" />
		<RemoveDir Directories="$(CopyDir)" />
	</Target>
    
</Project>